/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mySidebar: [
    {
      type: 'category',
      label: 'Guides',
      items: [
        {
          type: 'category',
          label: 'Integrate Logistics',
          link: {
            type: 'doc',
            id: 'guides/integrate-logistics',
          },
          items: [
            {
              type: 'link',
              label: 'Overview',
              href: '/guides/integrate-logistics#overview',
            },
            {
              type: 'link',
              label: 'Create a client account',
              href: '/guides/integrate-logistics#create-a-client-account',
            },
            {
              type: 'link',
              label: 'Calculating CO₂ emissions for a shipment',
              href: '/guides/integrate-logistics#calculating-co-emissions-for-a-shipment',
            },
            {
              type: 'link',
              label: 'Offsetting shipment emissions',
              href: '/guides/integrate-logistics#offsetting-shipment-emissions',
            }
          ]
        },

        {
          type: 'category',
          label: 'Integrate Payments',
          link: {
            type: 'doc',
            id: 'guides/integrate-payments',
          },
          items: [
            {
              type: 'link',
              label: 'Overview',
              href: '/guides/integrate-payments#overview',
            },
            {
              type: 'link',
              label: 'Create a client account',
              href: '/guides/integrate-payments#create-a-client-account',
            },
            {
              type: 'link',
              label: `Store a client's offsetting decision`,
              href: '/guides/integrate-payments#store-a-clients-offsetting-decision',
            },
            {
              type: 'link',
              label: 'Calculate contribution to CO₂ emission offsetting',
              href: '/guides/integrate-payments#calculate-contribution-to-co-emission-offsetting',
            }
          ]
        },

      ],
    },
    {
      type: 'category',
      label: 'Lune API',
      items: [
        {
          type: 'autogenerated',
          dirName: 'api'
        }
      ],
    },
    {
      type: 'category',
      label: 'Resources',
      items: [
        {
          type: 'autogenerated',
          dirName: 'resources',
        },
      ]
    }
  ],
};

module.exports = sidebars
