on:
  push:
    branches:
    - api-schema-update

jobs:
  api-update:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use node version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Lint
      run: yarn lint

    - name: API Reference update
      run: yarn api-reference

    # Changelog might have changed so update generated page automatically
    - name: Add changes
      run: |
        git add docs/key-concepts/changelog.md

    - name: Commit changes
      run: |
        git diff --cached --quiet || git commit -m "Update Changelog page"

    - name: Push changes
      run: |
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}

    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        github_token: ${{ secrets.API_TOKEN_GITHUB }}
        pr_title: "Update API reference"
        pr_body: "Pick up latest API schema"
        pr_reviewer: "lune-climate/engineering"
