on:
  push:
    branches:
    - api-schema-update

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"
        github_token: ${{ secrets.API_TOKEN_GITHUB }}
        pr_title: "Update API schema"
        pr_body: "[Please fill]"
        pr_reviewer: "lune-climate/engineering"
        pr_label: "API"
